name: eurokey2
description: Project files for the second version of the Eurokey app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_info_window: ^1.0.1
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.5.0
  onboarding: ^3.1.0
  geolocator: ^10.1.0
  introduction_screen: ^3.1.8
  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.2
  csv: ^5.0.2
  spreadsheet_decoder: ^2.2.0
  http: ^1.1.0
  rxdart: ^0.27.7
  google_maps_cluster_manager: ^3.0.0+1
  map_launcher: ^3.0.1
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.10
  flutter_scroll_to_top: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  yaml: ^3.1.2
  easy_search_bar: ^2.5.0
  archive: ^3.4.6
  location: ^5.0.3
  permission_handler: ^11.0.1
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  provider: ^6.1.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  lint: ^2.1.2
  test: ^1.24.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/map_styles/
